github pages deployment step updated

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -45,11 +45,11 @@ jobs:
       - name: Build
         run: npm run build
 
-      - name: "Upload artifacts"
-        uses: actions/upload-artifact@v3
-        with:
-          name: github-pages
-          path: './dist'
+      # - name: "Upload artifacts"
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: github-pages
+      #     path: './dist'
 
 #       - name: Upload artifact
 #         uses: actions/upload-pages-artifact@v1
@@ -57,6 +57,16 @@ jobs:
 #           # Upload entire repository
 #           path: '.'
 
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v1
+      # - name: Deploy to GitHub Pages
+      #   id: deployment
+      #   uses: actions/deploy-pages@v1
+      
+      - name: Deploy to gh-pages
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "GitHub Actions"
+          git branch -D gh-pages || echo "gh-pages branch not found"
+          git checkout -b gh-pages
+          git add dist/
+          git commit -m "Deploy to gh-pages"
+          git push -f origin gh-pages
